# Generated by Django 4.2.11 on 2025-05-30 20:36

from django.db import migrations, models
import shop1django.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop1django', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=shop1django.models.product_image_upload_path),
        ),
    ]
