# Generated by Django 4.2.7 on 2025-05-31 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop1django', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
